# Generated by Django 4.0.4 on 2022-06-13 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='image',
            field=models.ImageField(default='', upload_to='profile_image'),
            preserve_default=False,
        ),
    ]
