# Generated by Django 4.0.4 on 2022-06-06 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_categoria'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'verbose_name': 'categoria', 'verbose_name_plural': 'categorias'},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name': 'producto', 'verbose_name_plural': 'productos'},
        ),
        migrations.RenameField(
            model_name='products',
            old_name='active',
            new_name='is_active',
        ),
    ]
